# Generated by Django 3.0.4 on 2021-01-30 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import leave.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('sick_leave', 'SICK LEAVE'), ('annual_leave', 'ANNUAL LEAVE'), ('exam_leave', 'EXAMINATION LEAVE'), ('compassionate_leave', 'COMPASSIONATE LEAVE')], default=leave.models.default_type, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'ANNUAL LEAVE')], default=leave.models.default_status, max_length=20)),
                ('leave_start', models.DateTimeField()),
                ('leave_end', models.DateTimeField()),
                ('resumption_date', models.DateTimeField()),
                ('duration', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('manager_note', models.TextField(null=True)),
                ('status_updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('relieve_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_relieve_staff', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
